<?php
$posts = $this->params['posts'];
$currentPage = $this->params['currentPage'];
$totalPages = $this->params['totalPages'];

$previous = $currentPage - 1;
$next = $currentPage + 1;
$index = 0;
?>
<nav aria-label="Page navigation example">
    <ul class="pagination">
        <?php if ($previous): ?>
            <li class="page-item">
                <a class="page-link" href="<?= "?p=$previous" ?>" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
        <?php endif; ?>
        <?php while ($index != $totalPages) : ?>
            <?php $index++; ?>
            <li class="page-item <?= $currentPage == $index ? "active" : "" ?>"><a class="page-link" href="<?= "?p=$index" ?>"><?= $index ?></a></li>
        <?php endwhile; ?>
        <?php if ($next <= $totalPages) : ?>
            <li class="page-item">
                <a class="page-link" href="<?= "?p=$next" ?>" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        <?php endif; ?>
    </ul>
</nav>
<pre>
    <?= print_r($this->params, true) ?>

</pre>