
<main class="form-signin w-100 m-auto container text-centerl" style=" min-height: 80vh;">
    <div class="mb-3 col-md-4 mx-auto pt-5 justify-content-center">
        <form action="/user/login" method="POST">
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

        <div class="form-floating" bis_skin_checked="1">
            <input class="form-control" name="name">
            <label for="floatingInput">Name</label>
        </div>
        <div class="form-floating" bis_skin_checked="1">
            <input type="password" class="form-control" name="password" placeholder="Password">
            <label for="floatingPassword">Password</label>
        </div>

        <div class="form-check text-start my-3" bis_skin_checked="1">
            <input class="form-check-input" type="checkbox" value="remember-me" id="remember_me">
            <label class="form-check-label" for="flexCheckDefault">
                Remember me
            </label>
        </div>
        <button class="btn btn-primary w-100 py-2" type="submit">Sign in</button>
        <p class="mt-5 mb-3 text-body-secondary">© 2017–2024</p>
    </form>
    </div>
</main>