<Html>
<head>
    <title>
        Registration Page
    </title>
</head>
    <body>
    <br>
    <br>
        <form action="/user/create" method="POST">
            <label> Firstname </label>
            <input type="text" name="name" size="15"/> <br> <br>
            <br>
            Email:
            <input type="email" name="email"/> <br>
            <br> <br>
            Password:
            <input type="Password" name="password"> <br>
            <br> <br>
            Re-type password:
            <input type="Password" name="password"> <br> <br>
            <input type="submit" value="Submit"/>
        </form>
    </body>
</html>